# Generated by Django 3.0.5 on 2020-04-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findApp', '0002_auto_20200427_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='findApp.City', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
