# Generated by Django 3.0.5 on 2020-04-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findApp', '0003_auto_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='carModel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='findApp.CarModel', verbose_name='Марка авто'),
            preserve_default=False,
        ),
    ]
