# Generated by Django 3.0.5 on 2020-05-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findApp', '0005_auto_20200427_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сайт для поиска')),
            ],
            options={
                'verbose_name': 'Сайт для поиска',
                'verbose_name_plural': 'Сайты для поиска',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_adress', models.CharField(max_length=250, unique=True, verbose_name='Адрес для поиска')),
                ('carModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findApp.CarModel', verbose_name='Марка авто')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findApp.City', verbose_name='Город')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findApp.Site', verbose_name='Сайт для поиска')),
            ],
            options={
                'verbose_name': 'Адрес для поиска',
                'verbose_name_plural': 'Сайты для поиска',
            },
        ),
    ]
