# Generated by Django 3.0.5 on 2020-05-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findApp', '0006_site_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'Адрес для поиска', 'verbose_name_plural': 'Адреса для поиска'},
        ),
    ]
